---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /matescider/:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Mates Cider & Perry Company"
keywords:    "mates cider perry company producers minety wiltshire west country england uk artisan craft real "
description: "Mates Cider & Perry Company - Handcrafted West Country Cider"
source_link: "https://github.com/bloomonkey/matescider"
#favicon:     #put a path like: "img/favicon.ico"
#touch_icon:  #put a path like: "img/apple-touch-icon.png"
#google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'

  yellow: '#DBB919'
  yellow-dark: '#655403'
  yellow-light: '#FCE782'
  yellow-lightest: '#FCF5D4'

  green: '#78C717'
  green-dark: '#335C02'
  green-light: '#C4FA82'
  green-lightest: '#E8FAD2'

  red: '#DB5F19'
  red-dark: '#652603'
  red-light: '#FCAE82'
  red-lightest: '#FCE2D4'

kramdown:
  auto_ids:  false
